- name: Setup home server
  hosts: home_server
  become: true
  vars_files:
    - secrets.yaml
  roles:
    - common
    - ssh
    - ufw
    - docker
    - directories
    - services
    - cloudflare
