- name: Allow traffic from local network
  community.general.ufw:
    rule: allow
    from_ip: 192.168.0.0/24

- name: Allow traffic to SSH
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow traffic to HTTP
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow traffic to HTTPS
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Deny all incoming traffic
  community.general.ufw:
    default: deny
    direction: incoming

- name: Allow all outgoing traffic
  community.general.ufw:
    default: allow
    direction: outgoing

- name: Set UFW logging to 'low'
  community.general.ufw:
    logging: low

- name: Enable UFW
  community.general.ufw:
    state: enabled
